

```{r setup3, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Paula's code

## So what's actually going on in the yaml file?

See some more detail here. [https://github.com/ropenscilabs/CIsandbox/blob/master/github-actions-yaml-description.Rmd](https://github.com/ropenscilabs/CIsandbox/blob/master/github-actions-yaml-description.Rmd).


You can find the `yaml` code for issue messages here:
https://github.com/ropenscilabs/CIsandbox/blob/master/.github/workflows/issuesmessage.yaml

<details><summary>click me code</summary>
  <p>


        name: Triage
        on:
          issues:
            types: [opened]
        jobs:
          commentOnNewIssues:
            name: Comment On New Issues
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@master
              - name: Comment On New Issues
                uses: actions/github@v1.0.0
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                  args: comment "Thanks for your issue! we are going to work on that"

  </p>
</details>

Note: this and other examples are located on the Github actions repo: 
[https://github.com/actions/github](https://github.com/actions/github)
which serve as the actions-toolkit for common _GitHub automations_. ### Understanding parts of the yaml file

The parts of the yaml file that were tricky to understand:

`on` can be `issues`, `pull`, `pull_request` you can use one or many as `[pull, pull_request]`

`uses`: `actions/checkout@master` or for the first `actions/first-interaction@v1`

##

## The generated YAML file

When we ran `usethis::use_github_actions` we generated a `R-CMD-check.yaml` file in the `.github/workflows` folder. YAML is a configuration file that's meant to be read by both humans and machines. In this case, the YAML file tells GitHub what we want the action to do. Let's dig into the contents of this file to see what's going on:

```
on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
```

You can find full documentation about these parameters on [GitHub](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions), but we'll highlight a few key points here:

* The `on` parameter tells GitHub what should trigger this action. In this case, we want to check code whenever it is pushed, or on a pull request. The latter is particularly useful because if we're about to merge code into the master branch, we want it to pass tests!
* The `name` of the action should be something that helps us identify at a glance what the action is doing. This is shown on github.com in the Actions tab of the repository.
* `runs-on` tells GitHub what sort of environment should run the job. These environments are called "runners". GitHub supports Ubuntu, macOS and Windows Server, as well as support for self-hosted runners.
* `uses` allows us to run other actions as part of our action. In this case, we're calling on actions that are defined in other repositories. The first action checks out the contents of our repository, and the next sets up R.
* The remaining steps are the commands we want to run as part of our action, each with a name. Here's we're installing the dependencies of our package, as well as the `rcmdcheck` package we use to check the package in our repository. Finally, we're executing the command that checks the package.

You may also have added a badge to your README file. These badges change appearance automatically based on the outcome of the action. [You can read more on GitHub](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository).